<div id="dbContent">
 <h1>Introduzione al database</h1>
 <p>
Per coordinare il lavoro di realizzazione delle schede da parte dei vari curatori è stato necessario adottare un <acronym class="db" title="Un'applicazione client-server (letteralmente cliente-servente) è un tipo di applicazione di rete nel quale il computer cliente manda una richiesta ad un server o ad un sistema di database.">sistema client/server</acronym>. Questo sistema permette di centralizzare la struttura del database, in modo che il lavoro nella sua forma più aggiornata sia disponibile in tempo reale a tutti i ricercatori, evitando al contempo i possibili problemi di sincronizzazione che nascerebbero qualora si adottasse un database distribuito sulle singole macchine degli utilizzatori. Il server è basato sul sistema operativo GNU/Linux su architettura x86_64; la distribuzione adottata è Debian 4.0 Etch con kernel 2.6.26-amd64. Il database che ospita l'archivio sul lato server è PostgreSQL 8.3.7, al quale sono state aggiunte le estensioni PostGIS 1.3.3 per la gestione dei dati geografici. La connessione al database avviene attraverso un tunnel SSH per garantire una maggior sicurezza dei dati mediante la cifratura dei dati trasmessi. Il tunnel viene realizzato mediante OpenSSH per i sistemi operativi Linux e Mac OS/X, oppure Putty per Windows. I programmi utilizzati per la creazione del database sono pgAdmin III 1.8.4 e l'editing diretto da riga di comando tramite psql.<br/>
I programmi utilizzati per la gestione del database sono <a href="http://www.openoffice.org/it/" target="_blank" title="[Link esterno] Home page di Open Office"> OpenOffice.org 3.0</a>, <a href="http://www.pgadmin.org/" target="_blank" title="[Link esterno] Home page di pgAdminIII">pgAdmin III</a>, <a href="http://www.qgis.org/" target="_blank" title="[Link esterno] Home page di QuantumGIS">QuantumGIS 1.3.0</a>.<br/>
Si sottolinea peraltro che la struttura del database è sostanzialmente indipendente dal client utilizzato per accedervi, per cui se in futuro nascessero nuove esigenze risulterà comunque possibile accedere e gestire i dati mediante client diversi: l'accesso tramite ODBC ne permette l'uso con il grande numero client che supportano questo standard, o, ad esempio, i dati geografici potrebbero essere gestiti tramite uDig o anche con programmi di uso commerciale quali ArcGIS.</p>

<p>Il tipo di dati utilizzati per i campi delle tabelle prevede quasi ovunque stringhe di testo a lunghezza variabile ("varchar"), con alcuni campi di tipo data e booleano. A questi si aggiungono i dati di tipo geografico, che per l'ubicazione sono di tipo point, mentre per l'area di interesse è prevista la possibilità di inserire dati puntuali, lineari ed areali. I punti possono rappresentare localizzazioni puntuali oppure baricentri di aree più vaste, ma la geometria rimane la medesima. Il tipo testo viene inoltre utilizzato per creare campi con funzioni diverse: alfanumerico, a lista, a scelta multipla, numerico, data. I campi a scelta multipla si collegano ad altre tabelle integrative che, assieme al nucleo principale sopra descritto, costituiscono l'architettura del database. Ad esempio, il campo "Stato di conservazione", comune a tutte le tabelle, si collega ad una tabella specifica denominata appunto "Stato di conservazione", i cui campi corrispondono ai valori possibili che il campo suddetto può contenere (pessimo, cattivo, discreto, buono, ottimo). Alcune di queste tabelle, che chiamiamo "sussidiarie", sono chiuse (vale a dire che i campi stabiliti resteranno tali, come nell'esempio appena menzionato) mentre altre sono aperte (ovvero soggette ad integrazioni con l'aggiunta di ulteriori campi; il campo comune "Rilevatore", ad esempio, è collegato ad una scheda sussidiaria il cui numero di campi verrà presumibilmente integrato nel corso del lavoro). Le tabelle sussidiarie sono quelle che costituiscono i vincoli (cioè le possibilità di scelta) per il tipo di geometria, i servizi di consultabilità e reperibilità, il tipo di scheda e lo stato di conservazione; a queste si aggiungono le tabelle contenenti tutti i dati geografici, una relativa all'ubicazione ed una all'area di interesse, ed una tabella di metadati, utilizzata per descrivere esplicitamente i codici utilizzati per la creazione delle colonne del database.</p>

<p>Esistono inoltre due tabelle di vincolo sui dati geometrici e sul sistema di riferimento geografico, introdotte per default da <a href="http://postgis.refractions.net/" target="_blank" title="[Link esterno] Home page di PostGIS">PostGIS</a> in modo trasparente per l'utilizzatore e necessarie per il funzionamento del sistema. Tra le tabelle sussidiarie hanno una struttura particolare quelle collegate ai campi comuni "Ubicazione" (che indica la localizzazione fisica del bene o della fonte schedati) e “Area di interesse” (che indica l'area geografica sottesa alle informazioni di cui il bene o la fonte sono portatori). I curatori hanno ritenuto opportuno dedicare a questi campi delle schede ausiliarie specifiche, affinché esse possano essere utilizzate per la georeferenziazione dei singoli beni/fonti all'interno del sistema GIS che si propone. Tali informazioni geografiche, se confrontate con le informazioni cronologiche – anch'esse rappresentabili in un GIS – possono restituire graficamente la mappatura delle fonti in relazione ad un determinato periodo storico.</p>

</div>