<div id="fontiContent">
 <h1>Le fonti storico-territoriali</h1>
 <p>La ricerca ha preso in considerazione nove tipologie di fonti: <a href="fontiArchivistiche.php" title="link alla pagina delle fonti archivistiche">archivistiche</a>, <a href="fontiBibliografiche.php" title="link alla pagina delle fonti bibliografiche">bibliografiche</a>, <a href="fontiFotografiche.php" title="link alla pagina delle fonti fotografiche">fotografiche</a>, <a href="fontiArchitettoniche.php" title="link alla pagina delle fonti architettoniche">architettoniche</a>, <a href="fontiOrali.php" title="link alla pagina delle fonti orali">orali</a>, relative alla <a href="fontiCulturaMateriale.php" title="link alla pagina delle fonti relative alla cultura materiale">cultura materiale</a>, <a href="fontiArcheologiche.php" title="link alla pagina delle fonti archeologiche">archeologiche</a>, <a href="fontiStoricoArtistiche.php" title="link alla pagina delle fonti storico-artistiche">storico-artistiche</a>, <a href="fontiCartografiche.php" title="link alla pagina delle fonti cartografiche">cartografiche</a>, delle quali, nelle pagine dedicate, si specificano la natura e i criteri di schedatura. Ulteriori dettagli sulle singole schede e le voci che le compongono sono reperibili nel <strong>documento introduttivo</strong> scaricabile dalla sezione <a href="materiali.php" title="link alla pagina dei materiali disponibili per il download">materiali</a>.</p>
 <p>Il database è potenzialmente integrabile con ulteriori tipologie di fonti (si pensi, ad esempio, ai documenti video o alla musica popolare), che potrebbero essere, in futuro, oggetto di indagine e schedatura.</p>  
</div>
<div class="sezFonti" id="sezArchiv">
 <p class="sezFontiP">FONTI ARCHIVISTICHE</p>
 <div class="subSez" id="subArchiv">
  <h2>Premessa</h2>
  <p>La sezione "fonti archivistiche" ha previsto l'individuazione e la schedatura degli archivi, pubblici e privati, che conservano materiale relativo alla storia e al territorio di Primiero. Per archivio s'intende la raccolta ordinata degli atti di un ente o di un individuo costituitasi durante lo svolgimento delle attività politiche, culturali, sociali, economiche, amministrative di quell'ente o individuo, ma anche la raccolta "disordinata" di fotografie, materiale audiovisivo, scritture autobiografiche, lettere ecc. che si conservano negli archivi privati di famiglia, la cui individuazione e schedatura acquista un'importanza fondamentale per loro stessa natura sfuggente, ma spesso ricca di materiale suscettibile di un utilizzo come fonte storica.</p>
  <p>Nella schedatura si è tenuto conto della situazione di confine che ha caratterizzato la storia di Primiero influendo anche sulla "geografia delle fonti". Essa comprende due grandi aree: quella veneta e quella titolese-austriaca le quali, a seconda dei diversi periodi storici e dei campi di indagine, possono fornire materiale documentario e fonti scritte, dirette o preterintenzionali, sulla storia della valle. Gli archivi considerati sono quindi non solo quelli conservati in valle, ma anche quelli di Feltre, Trento, Bolzano, Innsbruck, Vienna, per citare solo i centri principali. </p>
  <p>Il criterio di individuazione è il puntuale riferimento alla valle ricostruibile, nel caso di archivi situati al di fuori del suo territorio, attraverso fonti edite o studi che si siano occupati della materia. L'arco cronologico considerato va dalle prime testimonianze scritte conservate alla contemporaneità, includendo tutti gli archivi storici, ma anche archivi privati di interesse storico. </p>
  <p>È stata segnalata l'esistenza di tutti gli archivi, anche se soggetti a vincolo archivistico e quindi non consultabili. </p>

  <h2>La schedatura </h2>
  <p>La scheda delle fonti archivistiche si organizza su due livelli dedicati rispettivamente agli archivi intesi come insiemi e ai fondi conservati al loro interno.<br/> Un terzo livello di approfondimento è stato apportato per consentire una descrizione specifica di singoli documenti.<br/>
  Nelle schede sono riportati i campi generali comuni e le voci d'interesse specifico per gli archivi e i fondi, con rimandi interni.</p>
 </div>
</div>
<div class="sezFonti" id="sezBiblio">
 <p class="sezFontiP">FONTI BIBLIOGRAFICHE</p>
 <div class="subSez" id="subBiblio">
  <h2>Premessa</h2>
  <p>La sezione "fonti bibliografiche" ha previsto l'individuazione e la schedatura delle fonti secondarie edite e inedite, delle edizioni di fonti e delle fonti   periodiche relative alla storia e al territorio di Primiero; operazioni fondamentali volte ad integrare e supportare il lavoro di reperimento delle fonti primarie.</p>
  <p>Per fonti secondarie si intende l'insieme della letteratura scientifica edita (monografie, saggi, articoli, recensioni, cataloghi) e non edita (tesi di laurea e di dottorato, inventari) che è frutto dello studio e dell'interpretazione delle fonti primarie. Le edizioni di fonti sono le opere a stampa in cui sono pubblicate delle fonti (principalmente archivistiche, ma anche orali, artistiche ecc.) normalmente corredate da un'introduzione, da saggi e/o da un apparato critico (note al testo) che rientrano nella categoria delle fonti secondarie. Le fonti periodiche (ascrivibili alla categoria delle fonti primarie a stampa) sono le pubblicazioni periodiche primierotte o comunque relative al territorio di Primiero (quindi sia quelle prodotte e pubblicate in loco, sia quelle più genericamente trentine) come i quotidiani provinciali, i giornali locali, i giornalini e i bollettini di enti locali pubblici e privati.</p>
  <p>È stato innanzitutto definito un criterio significativo per circoscrivere il campo delle fonti bibliografiche indicizzabili. Per quanto riguarda le fonti secondarie e le edizioni di fonti, si è ritenuto opportuno prendere in considerazione le opere che contengono espliciti riferimenti a Primiero o al suo territorio (paesi, valli, località del comprensorio) escludendo quindi dall'indice gli studi riguardanti, in senso generico, istituzioni od organismi statali sovraterritoriali che pure hanno incorporato Primiero nella loro compagine. Il lavoro rischierebbe altrimenti di estendersi oltre misura e soprattutto di risultare dispersivo e non sufficientemente utile allo scopo, che è quello di individuare uno specifico status quaestionis storiografico e scientifico sul territorio di Primiero e conseguentemente di fornire un preciso strumento di supporto alle future ricerche su di esso.</p>
  <p>Lo stesso criterio vale per le fonti periodiche, cessate o correnti. Da una parte verranno considerati i periodici primierotti e le pubblicazioni periodiche prodotte da enti e associazioni locali; dall'altra i quotidiani o i periodici provinciali che abitualmente dedicano o hanno dedicato uno spazio specifico al territorio di Primiero. </p>

  <h2>La schedatura</h2> 
  <p>All'interno dell'architettura del database, la schedatura delle singole fonti bibliografiche si articola al secondo livello di approfondimento, mentre il primo livello è dedicato a quelli che possono essere considerati come "insiemi di conservazione": vale a dire, principalmente, le biblioteche, i musei, le emeroteche. </p>
  <p>Si specifica che, essendo le biblioteche trentine coordinate e messe in relazione da un sistema unitario (SBT, Sistema Bibliotecario Trentino) e le opere ivi conservate indicizzate in un catalogo unico (CBT, Catalogo Bibliografico Trentino), tali biblioteche verranno considerate come insieme anche nella scheda di primo livello; verrà quindi indicizzato l'SBT, non la singola biblioteca, la cui indicazione ci è sembrata poco utile, a meno che l'opera schedata nel corrispondente secondo livello sia conservata solo nella biblioteca intercomunale di Fiera di Primiero, oppure sia un'opera antica, difficilmente reperibile, appartenente ad un fondo storico (normalmente della Biblioteca Comunale di Trento e della Biblioteca Civica di Rovereto: in questi casi si specifica la biblioteca di appartenenza.</p>
 </div>
</div>
<div class="sezFonti" id="sezFoto">
 <p class="sezFontiP">FONTI FOTOGRAFICHE</p>
 <div class="subSez" id="subFoto">
  <h2>Premessa</h2> 
  <p>Questa sezione comprende sia le fotografie storiche (conservate in collezioni e archivi pubblici e privati, ma anche pubblicate in libri e articoli), sia le immagini realizzate dai curatori del progetto nel corso del lavoro di schedatura. </p>

  <h2>La schedatura</h2>
  <p>I due livelli di schedatura sono stati modellati sulle tabelle delle fonti bibliografiche. Al secondo livello sono state schedate le singole fotografie, mentre il primo è dedicato agli "insiemi" che conservano tali fotografie: una collezione privata, un fondo archivistico, un articolo, un volume, un sito internet. Un'apposita scheda di primo livello è stata inoltre creata per l'archivio "Le fonti per la storia", ossia quello che contiene le immagini che documentano le fonti schedate dai curatori del progetto.</p>
 </div>
</div>
<div class="sezFonti" id="sezArchitett">
 <p class="sezFontiP">FONTI ARCHITETTONICHE</p>
 <div class="subSez" id="subArchitett">
  <h2>Premessa</h2>
  <p>Per fonte architettonica si intende esclusivamente il bene monumentale o architettonico del quale la soprintendenza per i beni architettonici della Provincia di   Trento riconosce la particolare importanza sottoponendolo a tutela.<br/>Diversamente da altre tipologie di fonti, la scelta di un riconoscimento formale per la definizione di fonte architettonica è motivata dalla volontà di distinguere chiaramente elementi monumentali e architettonici già sottoposti a tutela, da elementi che hanno simili caratteristiche e uguale importanza sotto il profilo storico-artistico ma non sottoposti a tutela. Questa distinzione formale permette innanzitutto di separare chiaramente tipologie di fonti simili (edifici nobili/edifici rurali, fontane monumentali/fontane storiche, ecc.); in secondo luogo pone l'accento sulla necessità di salvaguardare elementi storici che, sebbene fondamentali per la storia di un territorio, non sono ancora sottoposti a tutela e quindi figurano all'interno del progetto non quali fonti architettoniche, pur avendone il valore, bensì come fonti archeologiche.<br/>La scelta del limite geografico comprensoriale segue coerentemente l'indirizzo stabilito di concerto con gli altri curatori.</p>
  <h2>La schedatura </h2>
  <p>Il primo livello di schedatura corrisponde all'individuazione dei beni monumentali o architettonici sottoposti a tutela.<br/>Il secondo livello di schedatura è dedicato all'individuazione delle singole fasi architettoniche rinvenibili sul bene monumentale o architettonico.<br/>L'eventuale terzo livello di schedatura, per il momento non apportato, sarebbe rivolto ai singoli elementi architettonici di particolare interesse presenti all'interno di una fase architettonica, entro la quale rappresentano una caratteristica stilistica o un elemento datante (stili decorativi, aperture, iscrizioni, ecc.).</p>
 </div>
</div>
<div class="sezFonti" id="sezOrali">
 <p class="sezFontiP">FONTI ORALI</p>
 <div class="subSez" id="subOrali">
  <h2>Premessa</h2>
  <p>La strutturazione della scheda fonti orali parte dal presupposto che la fonte orale tendenzialmente considera e fornisce lo spunto per l'analisi di almeno due livelli di esperienza sociale: collettiva o di gruppo (classe, movimento ecc.) e individuale. L'atto del narrare è infatti sempre, allo stesso tempo, memoria autobiografica, trasmissione di una esperienza di vita e tradizione. La memoria soggettiva apparentemente non strutturata contiene sempre delle linee lungo le quali essa si condensa, cristallizza e organizza.</p>   
  <p>Partendo da questo presupposto è stata creata una ccheda che non considera la singola intervista come un atto isolato, individuale, ma la inserisce all'interno di una "esperienza" ampia creando così dei "gruppi di interviste" (questi coincideranno con i vari "archi orali" qualora le interviste appartengano già a delle raccolte chiuse; se invece sono state realizzate appositamente per la schedatura, sono stati creati dei nuovi "gruppi"). Si è quindi deciso di sviluppare la scheda su tre livelli, in modo tale da evidenziare e catalogare, oltre al contenuto della singola intervista e le caratteristiche performative e tecniche, anche una delle possibili linee attorno alle quali essa si "organizza" e "cristallizza".</p>

  <h2>La schedatura </h2>
  <p>Per la strutturazione della scheda si è preso spunto dai campi presenti nella scheda ministeriale per i Beni Demoetnoantropologici Immateriali (BDI): alcuni campi sono riportati singolarmente, altri raggruppati per snellire la scheda (i codici ministeriali sono sempre segnalati), altri ancora sono  aggiunti per avere una migliore contestualizzazione e per creare elementi comuni con le altre fonti.<br/> 
  I tre livelli sono così strutturati:<br/>
  Il primo livello segnala le caratteristiche dell'"archivio audio" per le interviste appartenenti a precise raccolte chiuse. Per quelle realizzate appositamente per il progetto "Le fonti per la storia" sono stati creati dei "gruppi" in base alla linea territoriale del "paese narrato": es. Gruppo Sagron, Gruppo Tonadico, Gruppo Canal San Bovo ecc.<br/>
  Il secondo livello considera la singola intervista. Vi vengono delineate le modalità di svolgimento (luogo, contesto, attrezzature e riversamento), le caratteristiche dell'informatore (modalità comunicativa, dati anagrafici) e dell'intervista (categoria, occasione di reperimento ecc.); sono poi riportati gli elementi di contenuto. La scheda non prevede la trascrizione del documento perché questa andrebbe a sostituire l'audio limitandone l'uso. È invece riportato l'indice degli elementi strutturali e delle unità logiche contenute nel bene. Verrà a crearsi un campo strutturato su tre colonne: la prima segmenta in maniera precisa il tempo di registrazione (es. 00h 34' 35''; 01h 5' 23''); la seconda segnala l'argomento trattato nei vari segmenti (es. produzione burro; situazione famigliare; festa patronale ecc.); la terza colonna riporta la parola chiave dell'argomento.<br/>
  Il terzo livello si concentra sugli elementi territoriali presenti a livello di contenuto. È stata creata un'apposita scheda per ogni "spazio narrato" nell'intervista: per essere meritevoli di schedatura i brani dovranno fornire elementi storici o aneddotici rilevanti dal punto di vista storico e culturale su di un particolare luogo (per esempio: strutture, sentieri, spazi aperti, località ecc.).</p>
 </div>
</div>
<div class="sezFonti" id="sezCultMat">
 <p class="sezFontiP">FONTI DELLA CULTURA MATERIALE</p>
 <div class="subSez" id="subCultMat">
  <h2>Premessa</h2>
  <p>La sezione "fonti della cultura materiale" riguarda l'individuazione, la schedatura e lo studio di manufatti, intesi come quegli oggetti che sono prodotti o alterati dall'uomo (per esempio gli utensili, i macchinari, le abitazioni, gli alimenti, i semi selezionati, i campi, le strade, e anche gli elementi del territorio), e si rivolge alla ricostruzione del quadro dei rapporti che intercorrono fra l'uomo, visto come collettività-comunità, e i suoi prodotti, delle pratiche produttive e delle relazioni che si creano fra i manufatti all'interno del sistema socio-economico e culturale. Come ambito cronologico si considererà soprattutto l'età moderna e contemporanea, con la possibilità di comprendere anche oggetti d'età medievale.<br/>  
  Si è voluto eseguire da un lato l'individuazione e il censimento delle collezioni museali e raccolte private di oggetti e dei lavori tipologici prodotti su contesti di fonti materiali (ad esempio le strutture insediative). L'operazione ricopre un ruolo sicuramente importante per quanto riguarda la conoscenza sia delle raccolte spontanee o "fai da te" presenti presso le abitazioni private, altrimenti ignorate, sia degli oggetti provenienti dal Comprensorio di Primiero e posti in collezioni museali lontane dal territorio d'origine. Il censimento può anche essere un'operazione preliminare alla progettazione di un'eventuale inventariazione di raccolte non musealizzate, di proprietà di enti locali. <br/>
  Dall'altro lato si è proposta un'analisi storica della rete di infrastrutture (strade principali e secondarie, mulattiere, sentieri, vie d'acqua, ecc.) da un punto di vista funzionale e tipologico, attraverso uno studio delle fonti documentarie relative (cartografia storica, catasti, fonti d'archivio, fonti orali) e una ricognizione per campioni sul territorio. Lo studio ha previsto un approccio analitico verso questi manufatti, e si spinge oltre la semplice individuazione. Sono stati esaminati campioni di infrastrutture, selezionandoli secondo le funzioni che ricoprono e in base al loro valore paesistico. Dall'analisi dettagliata delle singole unità si sono individuate le tipologie che le raggruppano. <br/>
  Le strutture viarie sono fondamentali per il movimento dell'uomo e sono funzionali alle sue attività: in ambiente montano collegano il fondovalle, la media e l'alta montagna, il paese con i masi e le malghe, con i luoghi di approvvigionamento di materie prime, di risorse foraggere e alimentari, con i siti produttivi. La scelta di quest'ambito non è affatto casuale, è una priorità:  l'ambiente "strade" si comporta di per sé come una struttura che lega numerosi nodi tematici relativi alla cultura materiale. Lo studio delle infrastrutture costituisce così la base sulla quale poi innestare e sviluppare altri temi sulle attività produttive, economiche e sociali.</p>

  <h2>La schedatura </h2>
  <p>Il sistema si schedatura si struttura su tre livelli. Il primo è rivolto all'individuazione delle collezioni/raccolte di oggetti e degli studi, in alcuni casi tipologici, o censimenti di categorie di manufatti. L'analisi della rete infrastrutturale si configura come studio tipologico ed è stata schedata e descritta al primo livello come progetto di ricerca specifico condotto appositamente per il progetto "Le fonti per la storia". Al secondo e terzo livello è stata sviluppata rispettivamente la parte dedicata alle tipologie di infrastrutture e quella riferita ai singoli manufatti viari presenti sul territorio. </p>
 </div>
</div>
<div class="sezFonti" id="sezArcheo">
 <p class="sezFontiP">FONTI ARCHEOLOGICHE</p>
 <div class="subSez" id="subArcheo">
  <h2>Premessa</h2>
  <p>In linea con i principi metodologici del progetto, per fonte archeologica non si intende esclusivamente l'oggetto recuperato dal sottosuolo, ma l'insieme delle informazioni che riguardano sia gli scavi archeologici e gli oggetti rinvenuti in stratigrafia o decontestualizzati, sia il territorio nella sua dimensione storica.<br/>
  L'insieme dei "beni archeologici" stricto sensu non è stato il punto di partenza della ricerca; essa si è infatti mossa da una visione globale di un complesso territoriale che ha subito mutamenti storici, dove la presenza dell'uomo ne ha segnato e plasmato i lineamenti. Il terreno, la sua trasformazione, il suo abbandono, il suo complesso iter evolutivo diventano quindi fonti da analizzare in una prospettiva archeologica. <br/>
  Il complesso dei reperti che sono stati rinvenuti nel territorio oggetto di ricerca ed i rispettivi siti, sono stati intesi, innanzitutto, come fonti portatrici di un significato storico-territoriale, equiparate, in una prospettiva di non gerarchia delle fonti, a tutte le altre informazioni che riguardano il territorio nella sua dimensione storica. La sezione "fonti archeologiche" prevede appunto l’individuazione e la schedatura di queste informazioni.<br/>
  Sono quindi stati schedati gli scavi archeologici effettuati nel Comprensorio di Primiero, i beni archeologici rinvenuti in essi, i ritrovamenti decontestualizzati avvenuti all'interno del territorio comprensoriale; la consultazione parallela di fonti non archeologiche (ad esempio bibliografie, fonti archivistiche catastali, cartografie ecc.) e la collaborazione con i curatori delle altre sezioni, hanno fornito ulteriori informazioni per la datazione di fonti (ad esempio di edifici rurali) o per la stessa loro individuazione (come nel caso di una strada antica della cui esistenza si hanno tracce solo in mappe storiche o di destinazioni d'uso di suoli desumibili da fonti d'archivio). <br/>
  La scelta del limite geografico comprensoriale, oltre a seguire coerentemente l'indirizzo stabilito di concerto con gli altri curatori, risponde ai criteri sempre più frequentemente utilizzati dall'archeologia contemporanea, ossia la tendenza a lavorare su territori omogenei e quindi necessariamente ridotti. </p>

  <h2>La schedatura </h2>
  <p>Il primo livello di schedatura corrisponde all'individuazione di indagini archeologiche (scavi archeologici o ricerche ad indirizzo archeologico, intesi come "insiemi" di siti archeologici).<br/>
  Il secondo livello è dedicato ai siti archeologici (intesi come singole fasi stratigrafiche archeologiche) .<br/>
  L'eventuale terzo livello di schedatura sarà rivolto alle singole fonti archeologiche, che quasi sempre corrispondono ai beni archeologici, ma possono essere anche singoli elementi di un "sito archeologico" che forniscono informazioni sulla datazione del sito stesso. </p>
 </div>
</div>
<div class="sezFonti" id="sezStorArt">
 <p class="sezFontiP">FONTI STORICO-ARTISTICHE</p>
 <div class="subSez" id="subStoArt">
  <h2>Premessa</h2>
  <p>La sezione “beni storico-artistici” prevede l’individuazione e la schedatura del patrimonio storico-artistico presente sul territorio di Primiero, con una apertura a quello ultraterritoriale che possa avere sotto diversi aspetti attinenza con Primiero in quanto fonte per la sua storia.<br/>
  Rientrano pertanto in questa sezione:</p>  
  <ul>
   <li>- le raccolte di musei, pinacoteche, gallerie e altri luoghi espositivi;
   <li>- le collezioni o serie di oggetti di interesse storico-artistico;
   <li>- gli affreschi, gli stemmi, i graffiti, le lapidi, le iscrizioni, i tabernacoli e gli altri ornamenti di edifici;
   <li>- le opere di pittura, scultura, grafica e qualsiasi oggetto d'arte.
  </ul>
  <p>Si è deciso di rispettare in linea di massima il terminus ante quem cronologico indicato dalla legislazione, escludendo dalla inventariazione di opere eseguite non oltre gli ultimi 50 anni. </p>

  <h2>La schedatura </h2>
  <p>Al fine di registrare i dati secondo criteri omogenei e condivisibili a livello nazionale, per la costruzione della scheda si sono rispettate qualora possibile le voci previste dagli standard ministeriali, sul modello delle schede OA per l'opera e l'oggetto d'arte. <br/>
  All'interno dell'architettura del database, la schedatura si articola in un primo e in un secondo livello di approfondimento: mentre il secondo livello è dedicato alla singola opera, il primo livello incorpora quelli che possono essere considerati "insiemi di conservazione": raccolte pubbliche o private, collezioni o serie, ma anche e soprattutto – considerato il numero esiguo di musei/collezioni pesenti sul territorio – "sistemi" coerenti in cui più oggetti d'arte sono presenti o collocati/custoditi (es. la casa privata decorata con diversi dipinti murali; la pieve...). Va rilevato a questo proposito che questi "insiemi" non verranno considerati nella loro qualità di beni architettonici (per i quali è previsto un trattamento specifico), ma trattati sotto l'aspetto prettamente funzionale di "collettori" di dati comuni dei singoli oggetti (collocazione, consultabilità, dati anagrafici...): infatti l'inventario vero e proprio si svilupperà sul II livello, ossia sull'individuazione e schedatura del singolo oggetto storico-artistico. Alla luce di ciò si spiega l'esiguità di informazioni specifiche del primo livello, che si limita di fatto alla sola denominazione dell'"insieme" (es. "chiesa arcipretale di Fiera") e a eventuali note: dato che, per restare nell'esempio, la chiesa arcipretale di Fiera non sarà valutata come oggetto in sé stesso, ma come "contenitore" di singole opere (es. "affresco parietale", "tabernacolo", "pala d'altare"...) che condividono alcuni dati comuni.</p>
 </div>
</div>
<div class="sezFonti" id="sezCarto">
 <p class="sezFontiP">FONTI CARTOGRAFICHE</p>
 <div class="subSez" id="subCarto">
  <h2>Da completare</h2>
  <p></p>
 </div>
</div>