<div id="progettoContent">
<p>&nbsp;</p>
 <p>Il progetto "Le fonti per la storia. Per un archivio delle fonti sulle valli di Primiero e Vanoi" propone l'<b>individuazione</b> e la <b>schedatura</b> di <a href="fonti.php" title="link alla pagina delle fonti storiche">nove tipologie di fonti</a> (<a>archivistiche</a>, <a>bibliografiche</a>, <a>fotografiche</a>, <a>architettoniche</a>, <a>orali</a>, relative alla <a>cultura materiale</a>, <a>archeologiche</a>, <a>storico-artistiche</a>, <a>cartografiche</a>) sulla storia delle valli di Primiero e Vanoi, al fine di promuoverne la conoscenza, la valorizzazione e lo studio, fornendo adeguati supporti per la ricerca.</p>

<p>Per far sì che fonti tanto eterogenee potessero essere coerentemente individuate, schedate e messe in relazione, è stata ideato un <big><b>database</b></big> <b>omogeneo</b>, <b>globale</b> ed <b>integrabile</b>, capace di raccogliere il lavoro di schedatura di tutti i curatori, pubblicato appunto su web per la massima fruizione.</p>

<p>Data la mole potenzialmente infinita delle fonti rilevabili, si è deciso di adottare un approccio che prevedesse un'individuazione progressiva dal generale al particolare; che considerasse quindi le fonti sia singolarmente intese, sia anche in quanto appartenenti ad insiemi e sottoinsiemi, a loro volta interpretabili come fonti. L’architettura generale del database riflette questo criterio di individuazione attraverso <b>tre livelli di approfondimento</b>, ad ognuno dei quali corrisponde una tabella di schedatura.<br>Il <b>primo livello</b> raccoglie le informazioni relative ad <a>insiemi di fonti</a> (archivi, collezioni di manufatti, gruppi di interviste, biblioteche, scavi archeologici, musei ecc.).<br>Le tabelle di <b>secondo livello</b> schedano le <a>unità contenute in tali insiemi</a> (un fondo archivistico, un saggio scientifico, un sito archeologico, un’opera d'arte, un singolo manufatto, un’ intervista, ecc.). Alcune tipologie di fonti hanno richiesto inoltre l'elaborazione di un <b>terzo livello</b> di approfondimento, eventualmente (ma non necessariamente) estensibile in futuro all'intero lavoro, nel quale <a>singole informazioni</a> riportate nella scheda di secondo livello vengono estrapolate ed ulteriormente approfondite.</p>

<p>La definizione e il contenuto dei vari livelli non è stata una scelta scontata ed immediata, ma è da considerarsi il frutto di una riflessione critica e del costante confronto tra le esigenze dei curatori. L'istanza primaria era, ed è, quella di affiancare alla <b>coerenza interna della singola scheda</b> nel proprio ambito disciplinare, la <b>coerenza logica dell'intero sistema</b>, ottenuta attraverso costanti ridefinizioni e aggiustamenti. Il risultato finale di questo processo è illustrato nel grafo relazionale della <a href="webgisPage.php" title="link alla pagina degli strumenti">sezione strumenti</a>.</p>

<p>In linea con la vocazione pluridisciplinare del progetto, i curatori hanno cercato di evidenziare i <b>collegamenti</b> esistenti tra le varie schede e di renderli immediatamente navigabili tanto in <b>senso verticale</b> (permettendo di percorrere i vari livelli di approfondimento), quanto in <b>senso trasversale</b> (mettendo quindi in comunicazione tra loro schede relative a fonti di diverso tipo). In ogni tabella di schedatura sono stati infatti predisposti degli appositi campi per contenere i <a>link</a> che aprono direttamente sia le schede appartenenti alla stessa “famiglia” (ossia quelle di livello superiore e/o inferiore), sia le schede di fonti di altra natura, ma tematicamente affini. Per la descrizione dettagliata di questo sistema di correlazione – come anche, più in generale, di tutti gli altri campi – si rimanda alle informazioni presenti nella pagina di <a>ricerca in un campo</a> della <a href="ricerche.php" title="link alla pagina del database">sezione database</a>.</p>

<p>La coerenza reciproca tra le singole fonti è stata inoltre necessaria per rendere possibile un ulteriore obiettivo centrale del progetto, ossia la creazione di un <big><b>WebGIS</b></big> (Geographic Information System) storico, basato sui dati geografici e cronologici delle fonti, uniformemente misurati. Il WebGIS storico consiste nel posizionamento delle singole fonti (e di tutte le informazioni contenute nelle relative tabelle di schedatura) in un ambiente geografico secondo coordinate spaziali e temporali. Se per le fonti archeologiche, storico-artistiche, materiali e architettoniche il ricorso a tale strumento è una prassi ormai consolidata, molto più raro è il suo impiego per le altre tipologie di fonti (bibliografiche, archivistiche, orali, fotografiche) prese in considerazione. </p>

<p>È per sfruttare al meglio le potenzialità del WebGIS che le schede contengono due diversi tipi di dati geografici: l’<b>ubicazione</b> e l’<b>area di interesse</b>.<br>
L’<b>ubicazione</b> è un dato puntiforme: essa indica l’attuale localizzazione fisica della fonte o del suo luogo di conservazione/raccolta (ad es. la sede di una biblioteca, di un archivio o di un museo, ecc.). 
Concettualmente molto diversa è l’<b>area di interesse</b>, con la quale si intende l'area geografica sottesa alle informazioni di cui il bene, la fonte o l'insieme di beni e fonti sono portatori (ad es., un diario di viaggio che descrive un valico montuoso avrà quest’ultimo come area di interesse ed una biblioteca come ubicazione). Ogni fonte può essere collegata a più aree (riprendendo l’ultimo esempio, il diario del viaggiatore conterrà informazioni su vari luoghi). 
La diversa natura delle fonti ha comportato l’utilizzo di varie forme geometriche per esprimere le aree di interesse: così l’area di interesse di una strada sarà una polilinea; quella di una fotografia, invece, un triangolo rappresentante il cono di ripresa dell’immagine; quella di un fondo archivistico, di un saggio o di un’intervista verrà invece rappresentata da un rettangolo, corrispondente ad una porzione di territorio più o meno estesa; quella di un bene architettonico o storico-artistico coinciderà sovente con la pianta di un edificio, e così via.</p> 

<p>Ulteriore caratteristica fondamentale del WebGIS, come accennato, è la sua <b>dimensione storica</b>: ogni area di interesse esprime non solo il contesto geografico di cui parla una determinata fonte, ma anche la collocazione temporale di quest’ultima. 
È molto importante specificare che la cronologia non è intesa, in questo progetto, semplicemente come datazione della fonte.  Il caso delle fonti bibliografiche od orali è illuminante, poiché per esse risulta imprescindibile considerare l’ambito cronologico degli argomenti trattati. Ad esempio, la cronologia di un saggio pubblicato nel 2008 concernente la seconda guerra mondiale, o quello di un'intervista registrata nel 1990 sullo stesso argomento, dovrà comprendere il periodo bellico – vale a dire l’<i>oggetto</i> delle fonti – e non semplicemente la data di pubblicazione del volume o di registrazione dell’intervista. Solo in questo modo, infatti, gli esempi qui riportati possono essere messi in relazione, nell'ottica di una ricerca cronologica, con le fonti archivistiche, fotografiche, storico-artistiche, archeologiche, architettoniche, materiali risalenti al medesimo periodo storico.</p> 

<p>Parallelamente alla compilazione delle schede è stata prevista la raccolta e la digitalizzazione di materiali conservati negli archivi privati, delle registrazioni audio o audiovisive realizzate per le interviste, delle foto eseguite dai curatori durante il lavoro di schedatura, al fine di costruire un <b>nuovo archivio virtuale</b> al quale in futuro si potrà accedere direttamente dal database attraverso specifici campi di collegamento.</p>
</div>
